version: "3.1"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    networks:
      - default
    depends_on:
      - db
  db:
    image: postgres:14.2
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - default

networks:
  default:
    driver: bridge
